const StockTransfer_Store={
   
    vicno: '',
    br: '',
    docno: '',
    per: 0,
    gross: 0,
    disc: 0,
    amount: 0,
    exp1:0,
    per1:0,
    adv: 0,
    N:1,
    stlamt: 0,
    cos: 0,
    ldiscount: 0,
    exgross: 0,
    exdisc: 0,
    examount: 0,
    cash: 0,
    cc: 0,
    chq: 0,
    bal: 0,
    post: 2,
    trntype: '',
    trn: '',
    trnid: 0,
    src: '',
    acno: '',
    accode: '',
    yyyymmdd: '',
    receipt:'',
    status:'',
    docdate:  new Date(),
    narration: '',
    ref: '',
    ref1: '',
    svicno: '',
    chq1: '',
    chq2: '',
    chq3: '',
    cc1: '',
    cc2: '',
    cc3: '',
    sid: '',
    vdate: new Date(),
    userid: '',
    iseditmode: false,
    vehclno: '',
    profit:'',
    profitper:'',
    statusname:'',
    ItemDetails:[]
    ,ItemDetails1:[]
    ,ItemDetails2:[] 
    ,ItemDetails3:[]
    ,ItemDetailsSales:[]
}
export default StockTransfer_Store
