const StockTransferItem_Store = {
        srno: 0,
        tno: '',
        vicno: '',
        docno: '',
        itemid: '',
        partno: '',
        stockqty:0,
        avgcost:0,
        brf:0, 
        sec: '',
        brand: '',
        idesc: '', 
        qty: 0,
        qty1: 0,
        unit: '',
        unitprice: '',
        total: 0, 
        io: '',
        src: '', 
        docdate: new Date,
        yyyymmdd: '',
        acno: '',
        br: '',
        brf: 0,  
        trntype: '',
        trn: '',
        costp: 0,
        fcind: 'AED',
        fcrate: 1,
        ltotal: 0,
        trnid: 0, 
        exprice: 0,
        extotal: 0, 
        sdisc:  0,
        costamt: 0
}
export default StockTransferItem_Store 